version: '3.8'

services:
  pandacare-fe:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3003:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=https://159.89.209.87
    restart: always
